<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaURL =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                ->getStore()
                ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeURL = $storeManager->getStore()->getBaseUrl();

/*
Rename images
Add hidden empty images for all links, load main image
when top hover load all images
when hover a paritcular link, call a fuction to change image and dl-lebel lin
*/
  
  
?>
<img class="rm_cl" style="display:none;" src="<?php echo $mediaURL; ?>porto_child/menu/rm_cl.jpg"/>
<img class="rm_cl_chandeliers" style="display:none;" src=""/>
<img class="rm_cl_flush" style="display:none;" src=""/>
<img class="rm_cl_linear" style="display:none;" src=""/>
<img class="rm_cl_mini" style="display:none;" src=""/>
<img class="rm_cl_pendants" style="display:none;" src=""/>
<img class="rm_cl_semi" style="display:none;" src=""/>


<script type="text/javascript">
	jQuery(document).ready(function(){
		window.dl_rm_cl_hovered=0;
		jQuery('.sw-megamenu.navigation li.level0:eq(1)').hover(function(){
			// hovered in
			if(window.dl_rm_cl_hovered == 0)
			{
				jQuery('.rm_cl_chandeliers').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_cl_chandeliers.jpg');
				jQuery('.rm_cl_flush').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_cl_flush.jpg');
				jQuery('.rm_cl_linear').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_cl_linear.jpg');
				jQuery('.rm_cl_mini').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_cl_mini.jpg');
				jQuery('.rm_cl_pendants').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_cl_pendants.jpg');
				jQuery('.rm_cl_semi').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_cl_semi.jpg');
				window.dl_rm_cl_hovered = 1;
			}
			dlcl_right_menu_set('Ceiling','.rm_cl','black',jQuery('.sw-megamenu.navigation li.level0:eq(1) ul.subchildmenu li a'),'600');
		},function(){
			// hovered out
		});
		
		function dlcl_hover(categoryText,categoryClass,color,handle,fontWeight)
		{
			if(jQuery(handle).html().indexOf(categoryText) !== -1)
			{	
				dlcl_right_menu_set(categoryText,categoryClass,color,handle,fontWeight);
			}
		}
		function dlcl_right_menu_set(categoryText,categoryClass,color,handle,fontWeight)
		{
			jQuery('.sw-megamenu.navigation li.level0:eq(1) .dl-menu-right-normal img').attr('src',jQuery(categoryClass).attr('src'));
			jQuery('.sw-megamenu.navigation li.level0:eq(1) .dl-menu-right-normal .dl-label-menu').html(categoryText);
			jQuery('.sw-megamenu.navigation li.level0:eq(1) .dl-menu-right-normal .dl-label-menu.dl-label').css('color',color);
			jQuery(handle).css('font-weight',fontWeight);
		}
		jQuery('.sw-megamenu.navigation li.level0:eq(1) ul.subchildmenu li a').hover(function(){
			// hovered in
				dlcl_hover('Chandeliers','.rm_cl_chandeliers','white',this,"700");
				dlcl_hover('Pendants','.rm_cl_pendants','black',this,"700");
				dlcl_hover('Mini Pendants','.rm_cl_mini','white',this,"700");
				dlcl_hover('Flush Mounts','.rm_cl_flush','black',this,"700");
				dlcl_hover('Semi Flush Mounts','.rm_cl_semi','black',this,"700");
				dlcl_hover('Linear Suspensions','.rm_cl_linear','black',this,"700");

			
				
		},function(){
			// hovered out
			//dlcl_right_menu_set('Ceiling','.rm_cl','black',jQuery('.sw-megamenu.navigation li.level0:eq(1) ul.subchildmenu li a'),'600');
			jQuery('.sw-megamenu.navigation li.level0:eq(1) ul.subchildmenu li a').css('font-weight','600');

		});

	})
</script>




<div class="dl-menu-right-normal">
	<img src="<?php echo $mediaURL; ?>porto_child/menu/rm_cl.jpg" alt="" />
	<div style="color:black;" class="dl-label dl-label-menu">Ceiling</div>
</div>
