<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaURL =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                ->getStore()
                ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeURL = $storeManager->getStore()->getBaseUrl();

/*
Rename images
Add hidden empty images for all links, load main image
when top hover load all images
when hover a paritcular link, call a fuction to change image and dl-lebel lin
*/
  
  
?>
<img class="rm_wa" style="display:none;" src="<?php echo $mediaURL; ?>porto_child/menu/rm_wa.jpg"/>
<img class="rm_wa_sconces" style="display:none;" src=""/>
<img class="rm_wa_vanity" style="display:none;" src=""/>
<img class="rm_wa_swing" style="display:none;" src=""/>


<script type="text/javascript">
	jQuery(document).ready(function(){
		window.dl_rm_wa_hovered=0;
		jQuery('.sw-megamenu.navigation li.level0:eq(2)').hover(function(){
			// hovered in
			if(window.dl_rm_wa_hovered == 0)
			{
				jQuery('.rm_wa_sconces').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_wa_sconces.jpg');
				jQuery('.rm_wa_vanity').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_wa_vanity.jpg');
				jQuery('.rm_wa_swing').attr('src','<?php echo $mediaURL; ?>porto_child/menu/rm_wa_swing.jpg');
				window.dl_rm_wa_hovered = 1;
			}
			dlwa_right_menu_set('Wall','.rm_wa','black',jQuery('.sw-megamenu.navigation li.level0:eq(2) ul.subchildmenu li a'),'600');
		},function(){
			// hovered out
		});
		
		function dlwa_hover(categoryText,categoryClass,color,handle,fontWeight)
		{
			if(jQuery(handle).html().indexOf(categoryText) !== -1)
			{	
				dlwa_right_menu_set(categoryText,categoryClass,color,handle,fontWeight);
			}
		}
		function dlwa_right_menu_set(categoryText,categoryClass,color,handle,fontWeight)
		{
			jQuery('.sw-megamenu.navigation li.level0:eq(2) .dl-menu-right-normal img').attr('src',jQuery(categoryClass).attr('src'));
			jQuery('.sw-megamenu.navigation li.level0:eq(2) .dl-menu-right-normal .dl-label-menu').html(categoryText);
			jQuery('.sw-megamenu.navigation li.level0:eq(2) .dl-menu-right-normal .dl-label-menu.dl-label').css('color',color);
			jQuery(handle).css('font-weight',fontWeight);
		}
		jQuery('.sw-megamenu.navigation li.level0:eq(2) ul.subchildmenu li a').hover(function(){
			// hovered in
				dlwa_hover('Sconces','.rm_wa_sconces','white',this,"700");
				dlwa_hover('Vanity Lights','.rm_wa_vanity','black',this,"700");
				dlwa_hover('Swing Arms','.rm_wa_swing','white',this,"700");

			
				
		},function(){
			// hovered out
			//dlwa_right_menu_set('Wall','.rm_wa','black',jQuery('.sw-megamenu.navigation li.level0:eq(2) ul.subchildmenu li a'),'600');
			jQuery('.sw-megamenu.navigation li.level0:eq(2) ul.subchildmenu li a').css('font-weight','600');

		});

	})
</script>




<div class="dl-menu-right-normal">
	<img src="<?php echo $mediaURL; ?>porto_child/menu/rm_wa.jpg" alt="" />
	<div style="color:black;" class="dl-label dl-label-menu">Wall</div>
</div>
