<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaURL =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                ->getStore()
                ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeURL = $storeManager->getStore()->getBaseUrl();

?>
<div class="container dlclcont">
	<div class="row dl_cl_mainrow">

		<div class="col-sm-3">
			<div class="dl-cat-bar-head">
			Accent
			</div>
			<div class="dl-cat-bar-subs">
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Step Lights</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Under Counter Lighting</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Picture Lights</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">LED Accent Lighting</a></div>
				
			</div>
		</div>

		<div class="col-sm-9 dlclcontr">
			<div class="row dl_cl_1c">
				<a href="<?php echo $storeURL; ?>accent.html?dl-listing=yes">
					<img src="<?php echo $mediaURL; ?>porto_child/cl/cla1.jpg"/>
					<div class="dl-label-complete">Shop All<br>Accent Lighting</div>
				</a>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/cla2.jpg"/>
						<div class="dl-label">Shop Step Lights</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/cla3.jpg"/>
						<div style="color:black;" class="dl-label">Shop Under Counter Lighting</div>
					</a>
				</div>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/cla4.jpg"/>
						<div class="dl-label">Shop Picture Lights</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/cla5.jpg"/>
						<div class="dl-label">Shop LED Accent Lighting</div>
					</a>
				</div>
			</div>


		</div>
	</div>

</div>

<?php
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
if ($request->getParam('dl-listing')=='yes')
{
	?>
		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('div.columns').show();
			
			})
			
		</script>
	<?php
}
else
{
	?>
		<script type="text/javascript">
		jQuery('div.category-view').show();
			
		</script>
	<?php
}



