<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaURL =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                ->getStore()
                ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeURL = $storeManager->getStore()->getBaseUrl();

?>
<script type="text/javascript">
jQuery(document).ready(function(){
	setInterval(dlSetHeight,500);
	

});
function dlSetHeight()
{
	jQuery(".dlhapp").height(jQuery(".dlhcopy").height()-2);
}
</script>
<div class="container dlclcont">
	<div class="row dl_cl_mainrow">

		<div class="col-sm-3">
			<div class="dl-cat-bar-head">
			Lamps
			</div>
			<div class="dl-cat-bar-subs">
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>lamps/table-lamps.html">Table Lamps</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>lamps/floor-lamps.html">Floor Lamps</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>lamps/task-lamps.html">Task Lamps</a></div>
				<div class="dl-cat-bar-subs-item"><a href="#">Accent Lamps (Coming Soon)</a></div>
				<div class="dl-cat-bar-subs-item"><a href="#">LED Lamps (Coming Soon)</a></div>
			</div>
		</div>

		<div class="col-sm-9 dlclcontr">
			<div class="row dl_cl_1c">
				<a href="<?php echo $storeURL; ?>lamps.html?dl-listing=yes">
					<img src="<?php echo $mediaURL; ?>porto_child/cl/cll1.jpg"/>
					<div class="dl-label-complete">Shop All<br>Lamps</div>
				</a>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>lamps/table-lamps.html">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/cll2.jpg"/>
						<div class="dl-label">Shop Table Lamps</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="<?php echo $storeURL; ?>lamps/floor-lamps.html">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/cll3.jpg"/>
						<div class="dl-label">Shop Floor Lamps</div>
					</a>
				</div>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>lamps/task-lamps.html">
						<img class="dlhcopy" src="<?php echo $mediaURL; ?>porto_child/cl/cll4.jpg"/>
						<div class="dl-label">Shop Task Lamps</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="#">
						<img class="dlhapp" src="<?php echo $mediaURL; ?>porto_child/cl/cll5.jpg"/>
						<div style="color:#000000" class="dl-label">Shop Accent Lamps (Coming Soon)</div>
					</a>
				</div>
			</div>

			<div class="row dl_cl_1c">
				<a href="#">
					<img src="<?php echo $mediaURL; ?>porto_child/cl/cll6.jpg"/>
					<div class="dl-label">Shop LED Lamps (Coming Soon)</div>
				</a>
			</div>

		</div>
	</div>
</div>


<?php
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
if ($request->getParam('dl-listing')=='yes')
{
	?>
		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('div.columns').show();
			
			})
			
		</script>
	<?php
}
else
{
	?>
		<script type="text/javascript">
		jQuery('div.category-view').show();
			
		</script>
	<?php
}



