<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaURL =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                ->getStore()
                ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeURL = $storeManager->getStore()->getBaseUrl();

?>
<div class="container dlclcont">
	<div class="row dl_cl_mainrow">

		<div class="col-sm-3">
			<div class="dl-cat-bar-head">
			Recessed
			</div>
			<div class="dl-cat-bar-subs">
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Housing</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Trims</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Kits</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Multiple Spots</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">Accessories</a></div>
				<div class="dl-cat-bar-subs-item"><a href="<?php echo $storeURL; ?>">LED Recessed Lighting</a></div>
			</div>
		</div>

		<div class="col-sm-9 dlclcontr">
			<div class="row dl_cl_1c">
				<a href="<?php echo $storeURL; ?>recessed.html?dl-listing=yes">
					<img src="<?php echo $mediaURL; ?>porto_child/cl/clr1.jpg"/>
					<div class="dl-label-complete">Shop All<br>Recessed Lights</div>
				</a>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/clr2.jpg"/>
						<div style="color:black" class="dl-label">Shop Housing</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/clr3.jpg"/>
						<div style="color:black" class="dl-label">Shop Trims</div>
					</a>
				</div>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/clr4.jpg"/>
						<div style="color:black" class="dl-label">Shop Kits</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/clr5.jpg"/>
						<div style="color:black" class="dl-label">Shop Multiple Spots</div>
					</a>
				</div>
			</div>

			<div class="row dl_cl_2c">
				<div class="col-xs-6 dl_cl_col_l">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/clr6.jpg"/>
						<div style="color:black" class="dl-label">Shop Accessories</div>
					</a>
				</div>
				<div class="col-xs-6 dl_cl_col_r">
					<a href="<?php echo $storeURL; ?>">
						<img src="<?php echo $mediaURL; ?>porto_child/cl/clr7.jpg"/>
						<div style="color:black" class="dl-label">Shop LED Recessed Lighting</div>
					</a>
				</div>
			</div>

		</div>
	</div>
</div>


<?php
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
if ($request->getParam('dl-listing')=='yes')
{
	?>
		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('div.columns').show();
			
			})
			
		</script>
	<?php
}
else
{
	?>
		<script type="text/javascript">
		jQuery('div.category-view').show();
			
		</script>
	<?php
}



