<script type="text/javascript">

jQuery(document).ready(function(){

	/*setTimeout(function(){
		jQuery('.filter-options-item').each(function( index, value ) {
		  if (jQuery(this).hasClass('active'))
		  {
		  	try{
				jQuery(this).find('.filter-options-title').click();
			}catch(e){}	
		  }
		});
		jQuery('.filter-options-item').each(function( index, value ) {
		  if (jQuery(this).hasClass('active'))
		  {
		  	try{
				jQuery(this).find('.filter-options-title').click();
			}catch(e){}	
		  }
		});
	},10000);*/
	
});
	



</script>