<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeURL = $storeManager->getStore()->getBaseUrl();

?>

<script type="text/javascript">
	/*
	call controller using ajax post
	



	*/
	jQuery(document).ready(function(){
		jQuery('.dl_home_b4_submit').click(newsletterButtonClick);
	});
	
	function newsletterButtonClick() {
		var emailField=jQuery('.dl_home_b4_text');
		var email = emailField.val();
		jQuery('.dl_home_b4_submit').val('Submitting');
		var request = jQuery.ajax({
		  url: "<?php echo $storeURL; ?>dlmigration/newsletter/new",
		  method: "POST",
		  data: { email : email }
		});
		 
		request.done(function( msg ) {
			jQuery('.dl_home_b4_submit').val('Submit');
		  	var jObject = /*jQuery.parseJSON(msg)*/msg;
		  	if (jObject == null)
		  	{
		  		alert('Error Occured');
		  		return;
		  	}
		  	var message = jObject.msg;
		  	if (message=='Please provide email')
		  	{
		  		emailField.val('Email field should not be empty');
		  	} else if (message == 'There was a problem with the subscription: Please enter a valid email address.')
		  	{
		  		
		  		emailField.val('Enter Valid Email');
		  	} else if (message == 'There was a problem with the subscription: This email address is already assigned to another user.')
		  	{
		  		//emailField.val('');
		  		emailField.val('Email assigned to other user');
		  	} else if (message == 'The confirmation request has been sent.')
		  	{
		  		//emailField.val('');
		  		emailField.val('Confirm Email');
		  	} else if (message == 'Thank you for your subscription.')
		  	{
		  		//emailField.val('');
		  		emailField.val('Thank you for subscribing!');
		  	}
		  	else
		  	{
		  		alert(message)
		  	}
		  	//Please provide email
		  	//There was a problem with the subscription: Please enter a valid email address.
		  	//There was a problem with the subscription: This email address is already assigned to another user.
		  	//The confirmation request has been sent.
		  	//Thank you for your subscription.

		});
		 
		request.fail(function( jqXHR, textStatus ) {
			jQuery('.dl_home_b4_submit').val('Submit');
		  alert( "Request failed: " + textStatus );
		});
	}


</script>